.

diff --git a/bin/usr/bin/gzexe b/bin/usr/bin/gzexe
--- a/bin/usr/bin/gzexe
+++ b/bin/usr/bin/gzexe
@@ -13,7 +13,7 @@
 # On Ultrix, /bin/sh is too buggy, change the first line to: #!/bin/sh5
 
 
-# Copyright (C) 1998, 2002, 2004, 2006-2007, 2010-2018 Free Software
+# Copyright (C) 1998, 2002, 2004, 2006-2007, 2010-2016 Free Software
 # Foundation, Inc.
 # Copyright (C) 1993 Jean-loup Gailly
 
@@ -36,17 +36,16 @@ nl='
 '
 IFS=" $tab$nl"
 
-version='gzexe (gzip) 1.10
-Copyright (C) 2007, 2011-2018 Free Software Foundation, Inc.
+version='gzexe (gzip) 1.8
+Copyright (C) 2007, 2011-2016 Free Software Foundation, Inc.
 This is free software.  You may redistribute copies of it under the terms of
-the GNU General Public License <https://www.gnu.org/licenses/gpl.html>.
+the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
 There is NO WARRANTY, to the extent permitted by law.
 
 Written by Jean-loup Gailly.'
 
 usage="Usage: $0 [OPTION] FILE...
-Replace each executable FILE with a compressed version of itself.
-Make a backup FILE~ of the old version of FILE.
+Rename each FILE with a compressed version of itself, renaming FILE to FILE~.
 
   -d             Decompress each FILE instead of compressing it.
       --help     display this help and exit
@@ -59,15 +58,15 @@ res=0
 while :; do
   case $1 in
   -d) decomp=1; shift;;
-  --h*) printf '%s\n' "$usage"   || exit 1; exit;;
-  --v*) printf '%s\n' "$version" || exit 1; exit;;
+  --h*) exec echo "$usage";;
+  --v*) exec echo "$version";;
   --) shift; break;;
   *) break;;
   esac
 done
 
 if test $# -eq 0; then
-  printf >&2 '%s\n' "$0: missing operand
+  echo >&2 "$0: missing operand
 Try \`$0 --help' for more information."
   exit 1
 fi
@@ -87,29 +86,29 @@ for i do
   esac
   if test ! -f "$file" || test ! -r "$file"; then
     res=$?
-    printf >&2 '%s\n' "$0: $i is not a readable regular file"
+    echo >&2 "$0: $i is not a readable regular file"
     continue
   fi
   if test $decomp -eq 0; then
     if sed -e 1d -e 2q "$file" | grep "^skip=[0-9][0-9]*$" >/dev/null; then
-      printf >&2 '%s\n' "$0: $i is already gzexe'd"
+      echo >&2 "$0: $i is already gzexe'd"
       continue
     fi
   fi
   if test -u "$file"; then
-    printf >&2 '%s\n' "$0: $i has setuid permission, unchanged"
+    echo >&2 "$0: $i has setuid permission, unchanged"
     continue
   fi
   if test -g "$file"; then
-    printf >&2 '%s\n' "$0: $i has setgid permission, unchanged"
+    echo >&2 "$0: $i has setgid permission, unchanged"
     continue
   fi
   case /$file in
   */basename | */bash | */cat | */chmod | */cp | \
-  */dirname | */expr | */gzip | \
-  */ln | */mkdir | */mktemp | */mv | */printf | */rm | \
+  */dirname | */echo | */expr | */gzip | \
+  */ln | */mkdir | */mktemp | */mv | */rm | \
   */sed | */sh | */sleep | */test | */tail)
-    printf >&2 '%s\n' "$0: $i might depend on itself"; continue;;
+    echo >&2 "$0: $i might depend on itself"; continue;;
   esac
 
   dir=`dirname "$file"` || dir=$TMPDIR
@@ -119,17 +118,13 @@ for i do
     type mktemp >/dev/null 2>&1
     mktemp_status=$?
   fi
-  case $dir in
-    */) ;;
-    *) dir=$dir/;;
-  esac
   if test $mktemp_status -eq 0; then
-    tmp=`mktemp "${dir}gzexeXXXXXXXXX"`
+    tmp=`TMPDIR=$dir mktemp`
   else
-    tmp=${dir}gzexe$$
+    tmp=$dir/gzexe$$
   fi && { cp -p "$file" "$tmp" 2>/dev/null || cp "$file" "$tmp"; } || {
     res=$?
-    printf >&2 '%s\n' "$0: cannot copy $file"
+    echo >&2 "$0: cannot copy $file"
     continue
   }
   if test -w "$tmp"; then
@@ -138,7 +133,7 @@ for i do
     writable=0
     chmod u+w "$tmp" || {
       res=$?
-      printf >&2 '%s\n' "$0: cannot chmod $tmp"
+      echo >&2 "$0: cannot chmod $tmp"
       continue
     }
   fi
@@ -161,15 +156,10 @@ trap 'res=$?
   (exit $res); exit $res
 ' 0 1 2 3 5 10 13 15
 
-case $TMPDIR in
-  / | /*/) ;;
-  /*) TMPDIR=$TMPDIR/;;
-  *) TMPDIR=/tmp/;;
-esac
 if type mktemp >/dev/null 2>&1; then
-  gztmpdir=`mktemp -d "${TMPDIR}gztmpXXXXXXXXX"`
+  gztmpdir=`mktemp -d`
 else
-  gztmpdir=${TMPDIR}gztmp$$; mkdir $gztmpdir
+  gztmpdir=/tmp/gztmp$$; mkdir $gztmpdir
 fi || { (exit 127); exit 127; }
 
 gztmp=$gztmpdir/$0
@@ -179,7 +169,7 @@ case $0 in
 */*) gztmp=$gztmpdir/`basename "$0"`;;
 esac || { (exit 127); exit 127; }
 
-case `printf 'X\n' | tail -n +1 2>/dev/null` in
+case `echo X | tail -n +1 2>/dev/null` in
 X) tail_n=-n;;
 *) tail_n=;;
 esac
@@ -189,13 +179,13 @@ if tail $tail_n +$skip <"$0" | gzip -cd > "$gztmp"; then
   (sleep 5; rm -fr "$gztmpdir") 2>/dev/null &
   "$gztmp" ${1+"$@"}; res=$?
 else
-  printf >&2 '%s\n' "Cannot decompress $0"
+  echo >&2 "Cannot decompress $0"
   (exit 127); res=127
 fi; exit $res
 EOF
     gzip -cv9 "$file") > "$tmp" || {
       res=$?
-      printf >&2 '%s\n' "$0: compression not possible for $i, file unchanged."
+      echo >&2 "$0: compression not possible for $i, file unchanged."
       continue
     }
 
@@ -207,32 +197,29 @@ EOF
     skip=[0-9] | skip=[0-9][0-9] | skip=[0-9][0-9][0-9])
       eval "$skip_line";;
     esac
-    case `printf 'X\n' | tail -n +1 2>/dev/null` in
+    case `echo X | tail -n +1 2>/dev/null` in
     X) tail_n=-n;;
     *) tail_n=;;
     esac
     tail $tail_n +$skip "$file" | gzip -cd > "$tmp" || {
       res=$?
-      printf >&2 '%s\n' "$0: $i probably not in gzexe format, file unchanged."
+      echo >&2 "$0: $i probably not in gzexe format, file unchanged."
       continue
     }
   fi
   test $writable -eq 1 || chmod u-w "$tmp" || {
     res=$?
-    printf >&2 '%s\n' "$0: $tmp: cannot chmod"
+    echo >&2 "$0: $tmp: cannot chmod"
     continue
   }
-  ln -f "$file" "$file~" 2>/dev/null || {
-    # Hard links may not work.  Fall back on rm+cp so that $file always exists.
-    rm -f "$file~" && cp -p "$file" "$file~"
-  } || {
+  ln -f "$file" "$file~" || {
     res=$?
-    printf >&2 '%s\n' "$0: cannot backup $i as $i~"
+    echo >&2 "$0: cannot backup $i as $i~"
     continue
   }
   mv -f "$tmp" "$file" || {
     res=$?
-    printf >&2 '%s\n' "$0: cannot rename $tmp to $i"
+    echo >&2 "$0: cannot rename $tmp to $i"
     continue
   }
   tmp=
diff --git a/bin/usr/bin/updatedb b/bin/usr/bin/updatedb
--- a/bin/usr/bin/updatedb
+++ b/bin/usr/bin/updatedb
@@ -1,6 +1,7 @@
 #! /bin/sh
 # updatedb -- build a locate pathname database
-# Copyright (C) 1994-2019 Free Software Foundation, Inc.
+# Copyright (C) 1994, 1996, 1997, 2000, 2001, 2003, 2004, 2005, 2006,
+# 2010, 2011 Free Software Foundation, Inc.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -13,7 +14,7 @@
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # csh original by James Woods; sh conversion by David MacKenzie.
 
@@ -21,46 +22,26 @@
 #set -x
 
 version='
-updatedb (GNU findutils) 4.7.0
-Copyright (C) 1994-2019 Free Software Foundation, Inc.
-License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
+updatedb (GNU findutils) 4.6.0
+Copyright (C) 2007,2008,2009,2010 Free Software Foundation, Inc.
+License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 This is free software: you are free to change and redistribute it.
 There is NO WARRANTY, to the extent permitted by law.
 
 Written by Eric B. Decker, James Youngman, and Kevin Dalley.
 '
 
-# File path names are not actually text, anyway (since there is no
-# mechanism to enforce any constraint that the basename of a
-# subdirectory has the same character encoding as the basename of its
-# parent).  The practical effect is that, depending on the way a
-# particular system is configured and the content of its filesystem,
-# passing all the file names in the system through "sort" may generate
-# character encoding errors in text-based tools like "sort".  To avoid
-# this, we set LC_ALL=C.  This will, presumably, not work perfectly on
-# systems where LC_ALL is not the way to do locale configuration or
-# some other seting can override this.
-LC_ALL=C
-export LC_ALL
 
-# We can't use substitution on PACKAGE_URL below because it
-# (correctly) points to https://www.gnu.org/software/findutils/ instead
-# of the bug reporting page.
 usage="\
 Usage: $0 [--findoptions='-option1 -option2...']
        [--localpaths='dir1 dir2...'] [--netpaths='dir1 dir2...']
        [--prunepaths='dir1 dir2...'] [--prunefs='fs1 fs2...']
        [--output=dbfile] [--netuser=user] [--localuser=user]
-       [--dbformat] [--version] [--help]
+       [--old-format] [--dbformat] [--version] [--help]
 
-Please see also the documentation at http://www.gnu.org/software/findutils/.
-Report (and track progress on fixing) bugs in the updatedb
-program via the GNU findutils bug-reporting page at
-https://savannah.gnu.org/bugs/?group=findutils or, if
-you have no web access, by sending email to <bug-findutils@gnu.org>.
-"
+Report bugs to <bug-findutils@gnu.org>."
 changeto=/
-
+old=no
 for arg
 do
   # If we are unable to fork, the back-tick operator will
@@ -78,42 +59,62 @@ do
     --output) LOCATE_DB="$val" ;;
     --netuser) NETUSER="$val" ;;
     --localuser) LOCALUSER="$val" ;;
+    --old-format) old=yes ;;
     --changecwd)  changeto="$val" ;;
     --dbformat)   dbformat="$val" ;;
     --version) fail=0; echo "$version" || fail=1; exit $fail ;;
     --help)    fail=0; echo "$usage"   || fail=1; exit $fail ;;
     *) echo "updatedb: invalid option $opt
-Try '$0 --help' for more information." >&2
+$usage" >&2
        exit 1 ;;
   esac
 done
 
-frcode_options=""
-case "$dbformat" in
-    "")
-        # Default, use LOCATE02
-        ;;
-    LOCATE02)
-        ;;
-    slocate)
-        frcode_options="$frcode_options -S 1"
-        ;;
-    *)
-        # The "old" database format is no longer supported.
-        echo "Unsupported locate database format ${dbformat}: Supported formats are:" >&2
-        echo "LOCATE02, slocate" >&2
-        exit 1
+
+
+
+case "${dbformat:+yes}_${old}" in
+    yes_yes)
+	echo "The --dbformat and --old cannot both be specified." >&2
+	exit 1
+	;;
+	*)
+	;;
 esac
 
-
-if true
-then
-    sort="/usr/bin/sort -z"
-    print_option="-print0"
-    frcode_options="$frcode_options -0"
-else
+if test "$old" = yes || test "$dbformat" = "old" ; then
+    echo "Warning: future versions of findutils will shortly discontinue support for the old locate database format." >&2
+    old=yes
     sort="/usr/bin/sort"
     print_option="-print"
+    frcode_options=""
+else
+    frcode_options=""
+    case "$dbformat" in
+	"")
+		# Default, use LOCATE02
+	    ;;
+	LOCATE02)
+	    ;;
+	slocate)
+	    frcode_options="$frcode_options -S 1"
+	    ;;
+	*)
+	    echo "Unsupported locate database format ${dbformat}: Supported formats are:" >&2
+	    echo "LOCATE02, slocate, old" >&2
+	    exit 1
+    esac
+
+
+    if true
+    then
+        sort="/usr/bin/sort -z"
+        print_option="-print0"
+        frcode_options="$frcode_options -0"
+    else
+        sort="/usr/bin/sort"
+        print_option="-print"
+    fi
 fi
 
 getuid() {
@@ -185,14 +186,12 @@ test -z "$PRUNEREGEX" &&
 : ${LOCATE_DB=/usr/var/locatedb}
 
 # Directory to hold intermediate files.
-if test -z "$TMPDIR"; then
-  if test -d /var/tmp; then
-    : ${TMPDIR=/var/tmp}
-  elif test -d /usr/tmp; then
-    : ${TMPDIR=/usr/tmp}
-  else
-    : ${TMPDIR=/tmp}
-  fi
+if test -d /var/tmp; then
+  : ${TMPDIR=/var/tmp}
+elif test -d /usr/tmp; then
+  : ${TMPDIR=/usr/tmp}
+else
+  : ${TMPDIR=/tmp}
 fi
 export TMPDIR
 
@@ -216,6 +215,8 @@ fi
 # The names of the utilities to run to build the database.
 : ${find:=${BINDIR}/find}
 : ${frcode:=${LIBEXECDIR}/frcode}
+: ${bigram:=${LIBEXECDIR}/bigram}
+: ${code:=${LIBEXECDIR}/code}
 
 make_tempdir () {
     # This implementation is adapted from the GNU Autoconf manual.
@@ -247,7 +248,7 @@ checkbinary () {
     fi
 }
 
-for binary in $find $frcode
+for binary in $find $frcode $bigram $code
 do
   checkbinary $binary
 done
@@ -287,6 +288,8 @@ fi
 rm -f $LOCATE_DB.n
 trap 'rm -f $LOCATE_DB.n; exit' HUP TERM
 
+if test $old = no; then
+# LOCATE02 or slocate format
 if {
 cd "$changeto"
 if test -n "$SEARCHPATHS"; then
@@ -317,7 +320,7 @@ if [ "$myuid" = 0 ]; then
     exit $?
   fi
 fi
-} | $sort | $frcode $frcode_options > $LOCATE_DB.n
+} | $sort -f | $frcode $frcode_options > $LOCATE_DB.n
 then
     : OK so far
     true
@@ -336,6 +339,75 @@ if test -s $LOCATE_DB.n; then
 else
   echo "updatedb: new database would be empty" >&2
   rm -f $LOCATE_DB.n
+fi
+
+else # old
+
+if temp_directory="`make_tempdir`"; then
+    bigrams="${temp_directory}"/bigrams
+    filelist="${temp_directory}"/filelist
+else
+    echo "failed to create temporary directory" >&2
+    exit 1
+fi
+
+rm -f $LOCATE_DB.n
+trap 'rm -f $LOCATE_DB.n; rm -rf "${temp_directory}"; exit' HUP TERM
+
+# Alphabetize subdirectories before file entries using tr.  James Woods says:
+# "to get everything in monotonic collating sequence, to avoid some
+# breakage i'll have to think about."
+{
+cd "$changeto"
+if test -n "$SEARCHPATHS"; then
+  if [ "$LOCALUSER" != "" ]; then
+    # : A5
+    su $LOCALUSER `select_shell $LOCALUSER` -c \
+    "$find $SEARCHPATHS $FINDOPTIONS \
+     \( $prunefs_exp \
+     -type d -regex '$PRUNEREGEX' \) -prune -o $print_option" || exit $?
+  else
+    # : A6
+    $find $SEARCHPATHS $FINDOPTIONS \
+     \( $prunefs_exp \
+     -type d -regex "$PRUNEREGEX" \) -prune -o $print_option || exit $?
+  fi
+fi
+
+if test -n "$NETPATHS"; then
+  myuid=`getuid`
+  if [ "$myuid" = 0 ]; then
+    # : A7
+    su $NETUSER `select_shell $NETUSER` -c \
+     "$find $NETPATHS $FINDOPTIONS \\( -type d -regex '$PRUNEREGEX' -prune \\) -o $print_option" ||
+    exit $?
+  else
+    # : A8
+    $find $NETPATHS $FINDOPTIONS \( -type d -regex "$PRUNEREGEX" -prune \) -o $print_option ||
+    exit $?
+  fi
+fi
+} | tr / '\001' | $sort -f | tr '\001' / > "$filelist"
+
+# Compute the (at most 128) most common bigrams in the file list.
+$bigram $bigram_opts < $filelist | sort | uniq -c | sort -nr |
+  awk '{ if (NR <= 128) print $2 }' | tr -d '\012' > "$bigrams"
+
+# Code the file list.
+$code "$bigrams" < "$filelist" > $LOCATE_DB.n
+
+rm -rf "${temp_directory}"
+
+# To reduce the chances of breaking locate while this script is running,
+# put the results in a temp file, then rename it atomically.
+if test -s $LOCATE_DB.n; then
+  chmod 644 ${LOCATE_DB}.n
+  mv ${LOCATE_DB}.n $LOCATE_DB
+else
+  echo "updatedb: new database would be empty" >&2
+  rm -f $LOCATE_DB.n
+fi
+
 fi
 
 exit 0
